// Copyright (c) 2012-2018 LG Electronics, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

#ifndef ERRORS_H_
#define ERRORS_H_

#define WCA_API_ERROR_NONE          0
#define WCA_API_ERROR_UNKNOWN           1
#define WCA_API_ERROR_MALFORMED_JSON        2
#define WCA_API_ERROR_INVALID_PARAMETERS    3
#define WCA_API_ERROR_CONNMAN_UNAVAILABLE   4
#define WCA_API_ERROR_WIFI_TECH_UNAVAILABLE 5
#define WCA_API_ERROR_CELLULAR_TECH_UNAVAILABLE 6
#define WCA_API_ERROR_WIFI_SWITCHED_OFF     7
#define WCA_API_ERROR_WAN_SWITCHED_OFF      8
#define WCA_API_ERROR_SCHEMA_VALIDATION     9

#define WCA_API_ERROR_INVALID_KEY       10
#define WCA_API_ERROR_AUTH_FAILED       11
#define WCA_API_ERROR_LOGIN_FAILED      12
#define WCA_API_ERROR_CONNECT_FAILED        13
#define WCA_API_ERROR_DHCP_FAILED       14
#define WCA_API_ERROR_PIN_MISSING       15
#define WCA_API_ERROR_OUT_OF_RANGE      16


#define WCA_API_ERROR_INTERNAL          100
#define WCA_API_ERROR_ALREADY_CONNECTING    101
#define WCA_API_ERROR_NETWORK_NOT_FOUND     102
#define WCA_API_ERROR_ALREADY_ENABLED       103
#define WCA_API_ERROR_ALREADY_DISABLED      104
#define WCA_API_ERROR_PROFILE_NOT_FOUND     105
#define WCA_API_ERROR_NO_SERVICE_CONNECTING 106
#define WCA_API_ERROR_DISCONNECT_FAILED     107
#define WCA_API_ERROR_SCANNING          108
#define WCA_API_ERROR_WPS_PIN           109
#define WCA_API_ERROR_CANCEL_WPS        110
#define WCA_API_ERROR_PEER_NOT_FOUND        111
#define WCA_API_ERROR_MULTI_CHAN_SCHED_MODE 112
#define WCA_API_ERROR_P2P_STATE_CHANGE      113
#define WCA_API_ERROR_P2P_DISABLED      114
#define WCA_API_ERROR_PERSISTENT_STATE      115
#define WCA_API_ERROR_LISTEN_STATE      116
#define WCA_API_ERROR_PEER_IN_ASSOC     117
#define WCA_API_ERROR_NOT_CONNECTED     118
#define WCA_API_ERROR_DISC_GROUP        119
#define WCA_API_ERROR_NO_ACTIVE_GRP     120
#define WCA_API_ERROR_GRP_NOT_FOUND     121
#define WCA_API_ERROR_DEVICE_NAME_UNSET     122
#define WCA_API_ERROR_WFD_STATE         123
#define WCA_API_ERROR_DEVICETYPE_INVALID    124
#define WCA_API_ERROR_DEVICETYPE        125
#define WCA_API_ERROR_SESSION_AVAIL_BIT     126
#define WCA_API_ERROR_CP_SUPPORT_BIT        127
#define WCA_API_ERROR_RTSP_PORT         128
#define WCA_API_ERROR_SUBSCRIPTION_REQD     129
#define WCA_API_ERROR_FINDSERVICE       130
#define WCA_API_ERROR_ADDSERVICE        131
#define WCA_API_ERROR_DELETESERVICE     132
#define WCA_API_ERROR_CANCEL_P2P_CONN       133
#define WCA_API_ERROR_DELETING_PROFILE      134
#define WCA_API_ERROR_LISTEN_PARAMS     135
#define WCA_API_ERROR_NO_CONNECTED_NW       136
#define WCA_API_ERROR_WIRED_WIFI_ONLINE     137
#define WCA_API_ERROR_WIRED_ONLINE      138
#define WCA_API_ERROR_WIFI_ONLINE       139
#define WCA_API_ERROR_WIRED_NOT_CONNECTED   142
#define WCA_API_ERROR_WIFI_NOT_CONNECTED    143
#define WCA_API_ERROR_FAILED_TO_CONNECT     144
#define WCA_API_ERROR_NOT_IMPLEMENTED       145
#define WCA_API_ERROR_TETHERING_ENABLE_FAILED 146
#define WCA_API_ERROR_TETHERING_DISABLE_FAILED 147
#define WCA_API_ERROR_TETHERING_SSID_FAILED         148
#define WCA_API_ERROR_TETHERING_PASSPHRASE_FAILED   149
#define WCA_API_ERROR_TETHERING_NO_SSID             150
#define WCA_API_ERROR_TETHERING_NO_PASSPHRASE       151
#define WCA_API_ERROR_TETHERING_SUPPORT_FAILED      152
#define WCA_API_ERROR_TETHERING_NOT_ALLOWED_TO_CHANGE_SEC_TYPE          153
#define WCA_API_ERROR_TETHERING_PASSPHRASE_WITH_OPEN_FAILED 154
#define WCA_API_ERROR_TETHERING_PASSPHRASE_INVALID  155
#define WCA_API_ERROR_COUNTER                  156
#define WCA_API_ERROR_TETHERING_RESTORE_WIFI_STATE_FAILED 157
#define WCA_API_ERROR_TETHERING_NOT_ALLOWED_TO_CHANGE_TIMEOUT 158
#define WCA_API_ERROR_TETHERING_TIMEOUT_NO_NEGATIVE_VALUES 159
#define WCA_API_ERROR_SET_PASSTHROUGH_PARAMS_FAILED  162
#define WCA_API_ERROR_FAILED_TO_ENABLE_DISABLE_TECHNOLOGIES 163
#define WCA_API_ERROR_FAILED_TO_SET_LISTEN_CHANNEL  164
#define WCA_API_ERROR_ALREADY_CONNECTED 165
#define WCA_API_ERROR_HOST_ROUTE_NOT_SET 166
#define WCA_API_ERROR_ETHERNET_TECHNOLOGY_UNAVAILABLE 167
#define WCA_API_ERROR_ETHERNET_TETHERING_ALREADY_ENABLED 168
#define WCA_API_ERROR_ETHERNET_TETHERING_ALREADY_DISABLED 169
#define WCA_API_ERROR_ETHERNET_TETHERING_SET 170
#define WCA_API_ERROR_REJECT_PEER 171
#define WCA_API_ERROR_LISTEN_PARAMS_INVALID_VALUES 172
#define WCA_API_ERROR_BLUETOOTH_TECHNOLOGY_UNAVAILABLE  173
#define WCA_API_ERROR_BLUETOOTH_SWITCHED_OFF            174
#define WCA_API_ERROR_NO_SERVICE_CONNECTED              175
#define WCA_API_ERROR_P2P_MULTIPLE_GROUPS_NOT_ALLOWED   176
#define WCA_API_ERROR_P2P_PASSPHRASE_INVALID            177
#define WCA_API_ERROR_WIFI_SCAN_INTERVAL_NEEDS_SUBSCRIPTION 178
#define WCA_API_ERROR_WIFI_PASSPHRASE_INVALID  179
#define WCA_API_ERROR_WIFI_SECURITY_TYPE_INVALID 180
#define WCA_API_ERROR_SET_TECHNOLOGY_STATE_NOT_SUPPORTED 181

#define WCA_API_ERROR_PROXY_FIND_PROXY_FOR_URL_ERROR    205
#define WCA_API_ERROR_FAILED_TO_SET_GO_INTENT           206

#endif /* ERRORS_H_ */
